import { Blog } from "@/types/blog";

const blogData: Blog[] = [
  {
    id: 1,
    title: "Durgadevi Enclave",
    bullet1: "Location: Happy Valley, Kengeri road.",
    bullet2: "Nature:  G +3.",
    bullet3: "No. of Flats: 48.",
    bullet4: "Builtup Area: 62,830 Sft.",
    image: "/images/blog/p1.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "2022 ",
  },
  {
    id: 2,
    title: "Eavetop Signature",
    bullet1: "Location: Padmanabha nagarL.",
    bullet2: "Nature:  G +4.",
    bullet3: "No. of Flats: 10.",
    bullet4: "Builtup Area: 15,000 Sft.",
    image: "/images/blog/p2.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "2022 ",
  },
  {
    id: 3,
    title: "Eavetop Serenity",
    bullet1: "Location: Nagarbhavi.",
    bullet2: "Nature:  G +4.",
    bullet3: "No. of Flats: 10.",
    bullet4: "Builtup Area: 15,000 Sft.",
    image: "/images/blog/p3.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "2021 ",
  },
  {
    id: 4,
    title: "V6 Enclave ",
    bullet1: "Location: Uttarahalli, Gublala.",
    bullet2: "Nature:  G +4.",
    bullet3: "No. of Flats: 80.",
    bullet4: "Builtup Area: 1,04,000 Sft.",
    image: "/images/blog/p4.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "2023 ",
  },
  {
    id: 5,
    title: "Eavetop Royal",
    bullet1: "Location: Kalkeri.",
    bullet2: "Nature:  G +3.",
    bullet3: "No. of Flats: 36.",
    bullet4: "Builtup Area: 43,500 Sft.",
    image: "/images/blog/p5.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "Ongoing.",
  },
  {
    id: 6,
    title: "Eavetop Square",
    bullet1: "Location: Vibhudipura,HAL.",
    bullet2: "Nature:  G +4.",
    bullet3: "No. of Flats: 30.",
    bullet4: "Builtup Area: 36,000 Sft.",
    image: "/images/blog/p6.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "Completion stage",
  },
  {
    id: 7,
    title: "Eavetop Pearl",
    bullet1: "Location: Nagarbhavi.",
    bullet2: "Nature:  G +4.",
    bullet3: "No. of Flats: 10.",
    bullet4: "Builtup Area: 12,000 Sft.",
    image: "/images/blog/p7.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "Ongoing",
  },
  {
    id: 8,
    title: "Eavetop Greens",
    bullet1: "Location: Koralur.",
    bullet2: "Nature:  Residential Plots.",
    bullet3: "No. of Plots: 50.",
    bullet4: "Builtup Area: N/A.",
    image: "/images/blog/p8.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "2020 ",
  },
  {
    id: 9,
    title: "V6 Golden Nest",
    bullet1: "Location: Nagarbhavi.",
    bullet2: "Nature:  G +4.",
    bullet3: "No. of Flats: 118.",
    bullet4: "Builtup Area: 1,53,400 Sft.",
    image: "/images/blog/p9.png",
    author: {
      name: "Year of completion",
      image: "/images/blog/eavetopLogo2.png",
      designation: "Eavetop Infra ",
    },
    publishDate: "2019",
  },
  
];
export default blogData;
